### ISSUE TITLE
Removing a toilet fails when auth is required

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#297]
## Problem

If a user goes to remove a toilet but is not authenticated, after they have logged in the app crashes.

## Reproducing

1. Log out
1. Attempt to remove a loo
1. Log in
1. The app crashes

## Error Details

![Failed state](https://user-images.githubusercontent.com/2150762/43398617-8414ad04-9400-11e8-8fef-67010f763a52.png)

### `api` error

```
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/home/harry/src/gbptm/node_modules/body-parser/lib/types/json.js:157:10)
    at parse (/home/harry/src/gbptm/node_modules/body-parser/lib/types/json.js:83:15)
    at /home/harry/src/gbptm/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/harry/src/gbptm/node_modules/raw-body/index.js:224:16)
    at done (/home/harry/src/gbptm/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/harry/src/gbptm/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### `api` error

```
uncaught at loosSaga at loosSaga 
 at takeLatest 
 at processPending 
 at report 
 ./src/api.js/api.reportLoo@http://localhost:3000/static/js/main.chunk.js:747:11
 index.js:1
```

**Comment by gailramster** [comment]
Occurs for me in this way with 2 errors in the process - noticed as map is reverting to my location after login. 
1. remove loo
2. log-in
3. Map reloads but has returned to my location, not the area I was looking at. - BUG
4. I go to area I was looking to remove a toilet from. 
5. Click on the toilet (which has not been removed)
6. Fetching toilet data screen appears. (screenshot). No toilets load. - BUG
7. Refreshing the page reloads toilets, though one I was removing is still there.
8. Remove toilet. 
![screen shot 2018-08-18 at 10 30 38](https://user-images.githubusercontent.com/2690575/44297944-ec3bb280-a2d1-11e8-8369-9df2c69ac5d7.png)

**Comment by ob6160** [comment]
Resolution here: https://github.com/neontribe/gbptm/pull/346/files
